<!DOCTYPE html>
<html lang="fr">
    <head>        
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Suivi du poids</title>
        <link href="style/style.css" rel="stylesheet">
    </head>
    <body>
        <header>
            <h1>Suivi du poids</h1>
        </header>
        <main>
            
        </main>
        <footer>
            <p>Suivi du poids</p>
        </footer>
    </body>
</html>